backend:
  name: github
  repo: ledlro-io/nuhro-thozhiyoor
  branch: main

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "posts"
    ...
    
backend:
  name: github
  repo: ledlro-io/nuhro-thozhiyoor
  branch: main
  app_id: $Ov23ligVTkbJekPXvgVr
